version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:remote

artifacts:
  files:
    - '**/*'
  base-directory: 'build'